# ------ root_path/dataset_name ------
root_path: '/home/dingkun/data/fs_data2/'

seed: 3407

# ------ Hyperparamters ------
search_hp: True

search_scale: [10, 7, 1]
search_step: [200, 20, 20]

init_beta: 1
init_alpha: 1
init_gamma: 0.1

eps: 0.001  # 0.005
training_feat_num: 400
training_free_feat_num: 400

w_training_free: [0.7, 0.3]
w_training: [0.2, 0.8]

# ------ Basic Config ------
dataset: 'sun397'
backbone: 'ViT-B/16'

lr: 0.0001
augment_epoch: 10
train_epoch: 30
