# ------ root_path/dataset_name ------
root_path: '/home/dingkun/data/fs_data2'

# ------ Basic Config ------
dataset: 'fashionmnist'
shots: 16
backbone: 'RN50'

subsample_classes: 'all'
augment_epoch: 10