# ------ root_path/dataset_name ------
root_path: '/home/dingkun/data/fs_data2/'

# ------ Basic Config ------
dataset: 'food101'
shots: 16
backbone: 'ViT-B/16'

subsample_classes: 'all'
augment_epoch: 10