# ------ root_path/dataset_name ------
root_path: '/home/dingkun/data/fs_data2/'

# ------ Basic Config ------
dataset: 'imagenet'
shots: 16
backbone: 'RN101'

subsample_classes: 'all'
augment_epoch: 10